### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "firstName": "sammy",
  "lastName": "luna",
  "email": "sam@mail.com",
  "password": "sam@12345",
  "ProfileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "sam@mail.com",
  "password": "sam@12345"
  
}

### User read all articles
GET http://localhost:4000/user-api/articles


###add comments
POST http://localhost:4000/user-api/articles/:articleId/comments



### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "Vikas",
  "lastName": "Author",
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  "ProfileImageUrl": "https://example.com/avatars/author.png"
}


### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "Author",
  "email": "test.author@example.com",
  "password": "testauthor",
  "ProfileImageUrl": "https://example.com/avatars/author.png"
}

### Author Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  
}



### Create article (AUTHOR)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"6989ef4eb3acfbbf9f926145",
  "title":"test2 article",
  "category":"programming",
  "content":"content of test2 article"
}



###Read articles of a author
GET http://localhost:4000/author-api/articles/6989ef4eb3acfbbf9f926145



### Update article (AUTHOR)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"6989ef4eb3acfbbf9f926145",
  "articleId":"6989f222a6212138f1ee0bde",
  "title":"test2 article updated",
  "category":"programming",
  "content":"content of test2 article updated"
}



### Logout
GET  http://localhost:4000/common-api/logout

###
GET http://localhost:4000/test

### blocking user
PUT  http://localhost:4000/admin-api/block/6989e719480e079c33d3a529
Content-Type: application/json

{
  
"email":"sam@mail.com",
"password":"$2b$10$yWGGIEhrE.sj1UiZRWvQaOy1WX7wZ6JSF2hIkcV9cc/ptQClA6UDa",
"role":"USER",
"isActive":true

}

###unblocking user
PUT  http://localhost:4000/admin-api/unblock/6989e719480e079c33d3a529
Content-Type: application/json

{
  
"email":"sam@mail.com",
"password":"$2b$10$yWGGIEhrE.sj1UiZRWvQaOy1WX7wZ6JSF2hIkcV9cc/ptQClA6UDa",
"role":"USER",
"isActive":true

}


###changing password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
  "userId":"6989e719480e079c33d3a529",
  "currentPassword": "sam@12345",
  "newPassword":"sammy@24"
}


