### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "Sam",
  "lastName": "K",
  "email": "sam2@gmail.com",
  "password": "123456"
}

### Author Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "sam2@gmail.com",
  "password": "123456"
  
}



### Create article (AUTHOR)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"69b434d17af5d453375ad443",
  "title":"sam 1 article",
  "category":"programming",
  "content":"content of test2 article"
}



###Read articles of a author
GET http://localhost:4000/author-api/articles/69b434d17af5d453375ad443



### Update article (AUTHOR)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"69b434d17af5d453375ad443",
  "articleId":"69b435377af5d453375ad448",
  "title":"The Art of Writing Clean Code",
  "category":"programming",
  "content":"Programming is not just about making the computer run instructions. It is about solving problems in the most efficient and understandable way possible. Many beginners focus only on making their code work, but experienced developers understand that writing clean and readable code is just as important as writing functional code."
}
### delete article
PATCH http://localhost:4000/author-api/articles/69ae8fd8170e0d5d18e82687/status
Content-Type: application/json


{"isArticleActive":true}

### Logout
post http://localhost:4000/common-api/logout

###changing password
PUT http://localhost:4000/common-api/change-password
Content-Type: application/json

{
  "role":"AUTHOR",
  "email":"sam2@mail.com",
  "currentPassword": "12345",
  "newPassword":"sam@123"
}
